title: F1rstdata.net Data Processing Systems
author: jlopez104545
email: jlopez104545@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Thank you for visiting the F1rstdata.net page! Increase your
  production rate improve overall performance with a 30-day free trial!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  modern105454 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
